### ISSUE TITLE
更换更可靠的接口

### ISSUE THREAD

**Issue by ZhiyuanChen** [wuhan-support/wuhan.support#2]
现在使用的 https://server.toolbon.com/home/tools/getPneumonia 存在调用数量限制，据说可以通过登陆解决但注册帐号无法通过邮箱验证……

**Comment by ZhiyuanChen** [comment]
ebea3c15d265a8a3951136bc416d316d97ed9c7e

**Comment by GalvinGao** [comment]
可使用BeautifulSoup直接抓取丁香园的页面中特定script标签的内容，写一个正则匹配出数据即可做json解析

**Comment by ZhiyuanChen** [comment]
3568b27cef446c6cdd66ff4383714ade94149be6
