### ISSUE TITLE
通过csv表格自动生成接受捐助的医院页面

### ISSUE THREAD

**Issue by ZhiyuanChen** [wuhan-support/wuhan.support#3]
是否有必要通过表格自动生成？
手打是否有些慢？

**Comment by ZhiyuanChen** [comment]
并且这样一来可以制作总表，即一个项目对应多家医院，方便捐助人找到信息

**Comment by leelaylay** [comment]
建议通过表格自动生成，那样UI可能也得调整下。

**Comment by ZhiyuanChen** [comment]
https://github.com/wuhan-support/wuhan.support/commit/3d0e1cbfa7d86f1bb6358c235c93dab881e6ef4c

**Comment by yc-zc** [comment]
3d0e1cb

**Comment by ZhiyuanChen** [comment]
ddde4a50294a5914d0f5eb0365df31fce4e96c5d
