### ISSUE TITLE
Investigate the "Chinese Red Cross"

### ISSUE THREAD

**Issue by WenjieZ** [wuhan-support/wuhan.support#32]
全世界的医药物资都填补不了武汉的空洞。

有经济学家认为红十字会故意封锁救援物资，造成一线医疗物资匮乏的现象，从而吸纳更多的捐助谋取私利。

不管这是不是真的，红十字会已经成为这场瘟疫战争的障碍，有必要对红十字会进行监督与审查。

**Comment by ZhiyuanChen** [comment]
这个恐怕不是我们所能做到的
/close
