### ISSUE TITLE
README.md 里微信大群二维码链接失效

### ISSUE THREAD

**Issue by toto6321** [wuhan-support/wuhan.support#33]
原因是这个图片地址已失效　https://feiyan.help/images/qr_volunteers.png

**Comment by ant-caichu** [comment]
@toto6321 可以提供图片的正确地址嘛？，我来提交个PR解决下。

**Comment by toto6321** [comment]
我不知道正确的地址呢 /笑哭　我如果知道就直接提PR了

**Comment by XYJeff** [comment]
大群里群简介的信息组群的邀请二维码我换成新的了，但是我不在技术组和宣传组里面没有办法拿到二维码

**Comment by ZhiyuanChen** [comment]
我错了qwq
这就更新
/meow
