### ISSUE TITLE
wuhan.support 链接失效

### ISSUE THREAD

**Issue by laubonghaudoi** [wuhan-support/wuhan.support#36]
https://wuhan.support/ 这个链接已经打不开，是什么原因？

另外想问一下，网站是部署在境内服务器还是境外服务器上？部署在境内的话有可能会被官方取缔，在境外的话则有可能被封杀。

**Comment by ZhiyuanChen** [comment]
hmmmmm
这个我没有遇到（肉身在墙内，可能是运营商的问题？我回头换个dns试试
咱们目前所有东西都在国外
