### ISSUE TITLE
湖北省医院信息整理

### ISSUE THREAD

**Issue by ZhiyuanChen** [wuhan-support/wuhan.support#6]
- [x] 湖北省武汉市
- [ ] 湖北省黄石市、襄樊市
- [ ] 湖北省十堰市、荆州市、宜昌市
- [ ] 湖北省荆门市、鄂州市、孝感市
- [ ] 湖北省黄冈市、咸宁市、随州市
- [ ] 湖北省恩施土家族苗族自治州、仙桃市、神农架林区

**Comment by NeverMin** [comment]
@yc-zc 目前医院是由信息组收集的吗? 请让我知道进度, 看我从哪接手比较合适? 谢谢

**Comment by ZhiyuanChen** [comment]
信息是由信息组收集的
目前湖北省已经收集完毕并上线，本issue现在关闭。
