### ISSUE TITLE
微信小程序前端

### ISSUE THREAD

**Issue by ZhiyuanChen** [wuhan-support/wuhan.support#7]

**Comment by jianzhe2011** [comment]
只学过一点关于微信小程序的，估计要用到什么知识呢？有大佬指明一下吗，晚上加加班。

**Comment by zikuanqi** [comment]
蔡老板还不会吗

**Comment by jianzhe2011** [comment]
> 蔡老板还不会吗
![u=614017937,283511089 fm=26 gp=0](https://user-images.githubusercontent.com/49832949/73121628-085b7d00-3fb7-11ea-9e3e-1f5ddfde31f7.jpg)

我没写过项目。。。。
