### ISSUE TITLE
一个关于物资捐赠信息平台提议

### ISSUE THREAD

**Issue by tonychenxyz** [wuhan-support/wuhan.support#8]
目前好像挺多医院，特别是武汉的医院非常缺防护物资。同时我看到很多医院发布的募捐信息与国内外很多想要或正在捐赠物资的人。特别是很多国外的物资，已经准备好，但需要快速的人肉搬运。我认为目前我们作为程序员能够做的非常大意义的一件事是搭建一个中心化的此类信息发布平台。通过我们所整理的医院信息，给各个医院提供发布募捐信息，捐赠者寻找捐赠对象，运输方（国内的货车，海外的航空公司）提供运输的统一途径，避免信息的分散化，提高物资输送效率。不知道大家怎么想。

**Comment by tonychenxyz** [comment]
刚刚看到一个类似的基于表格的repo：https://github.com/wuhan2020/wuhan2020
但我觉得可以做得更方便使用

**Comment by ZhiyuanChen** [comment]
> 刚刚看到一个类似的基于表格的repo：https://github.com/wuhan2020/wuhan2020
> 但我觉得可以做得更方便使用

是

> 目前好像挺多医院，特别是武汉的医院非常缺防护物资。同时我看到很多医院发布的募捐信息与国内外很多想要或正在捐赠物资的人。特别是很多国外的物资，已经准备好，但需要快速的人肉搬运。我认为目前我们作为程序员能够做的非常大意义的一件事是搭建一个中心化的此类信息发布平台。通过我们所整理的医院信息，给各个医院提供发布募捐信息，捐赠者寻找捐赠对象，运输方（国内的货车，海外的航空公司）提供运输的统一途径，避免信息的分散化，提高物资输送效率。不知道大家怎么想。

医院信息在hospitals.csv当中，我们目前最需要的就是通过补充这些信息。已经有了generate_hospitals.md来根据csv文件直接生成咱们的静态页面

**Comment by ZhiyuanChen** [comment]
> 刚刚看到一个类似的基于表格的repo：https://github.com/wuhan2020/wuhan2020
> 但我觉得可以做得更方便使用

这个非常好，我已经联系他们了

**Comment by liwen-tj** [comment]
两位知道具体每家医院需要每种物资数量的详细信息吗？

**Comment by tonychenxyz** [comment]
> 两位知道具体每家医院需要每种物资数量的详细信息吗？

另外一个repo的作者正在整理，且进度好像还行，然后应该尽快在前端搭建起以后增加用户数，直接从前端应用收集信息。
